# This is a basic workflow to help you get started with Actions

name: gradle graalvm native image windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          distribution: "graalvm" # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}

          components: "native-image"
      - run: java -version
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        # with:
        #   vs-prerelease: true
      # Runs a set of commands using the runners shell
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 # v4.0.0
        with:
          gradle-version: "8.12"
      #
      - name: Build with Gradle 8
        run: gradle build "-Dorg.gradle.jvmargs=--enable-native-access=ALL-UNNAMED" --stacktrace  --debug #--scan
      - name: Run a gradle script
        run: |
          gradle nativeCompile "-Dorg.gradle.jvmargs=--enable-native-access=ALL-UNNAMED"
      - name: "Tar files"
        run: |
          cd  build/native/nativeCompile
          tar -zcvf fast-and-mercury-router-reverse-proxy-server-windows.tgz fast-and-mercury-router-reverse-proxy-server.exe
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: fast-and-mercury-router-reverse-proxy-server-windows.tgz

          path: build/native/nativeCompile/fast-and-mercury-router-reverse-proxy-server-windows.tgz
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/master')
        with:
          tag_name: Continuous-integration-${{ github.sha }}
          #token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            build/native/nativeCompile/fast-and-mercury-router-reverse-proxy-server-windows.tgz
